ALTER TABLE upload_logs ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'success';
ALTER TABLE upload_logs ADD COLUMN IF NOT EXISTS message VARCHAR(255) NULL;
ALTER TABLE upload_logs ADD COLUMN IF NOT EXISTS total_rows INT NOT NULL DEFAULT 0;
ALTER TABLE upload_logs ADD COLUMN IF NOT EXISTS processed_rows INT NOT NULL DEFAULT 0;
